# instance              type                  ip
zigbee-gw               ewelink-zigbee-gw     10.1.30.46
garage-door             athom-garage-door     10.1.30.47

yeelight-1s             yeelight-1s           10.1.30.50
bslamp-primary          mi-bedside-lamp2      10.1.30.51
bslamp-secondary        mi-bedside-lamp2      10.1.30.52

lounge-ac               esp8266-ir-remote     10.1.30.74

atom-s3-ble-91          atom-s3-bleproxy      10.1.30.91
atom-s3-ble-92          atom-s3-bleproxy      10.1.30.92